on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Set CI Environment Variable
        run: echo "CI=true" >> $GITHUB_ENV
     
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Build
        run: |
          npm install
          npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: samnivesha
          directory: build

